# Generated by Django 4.0.4 on 2022-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='DNI',
            field=models.IntegerField(unique=True),
        ),
    ]
